apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecom-ingress
  namespace: ecom-prod
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: ecom.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ecom-service
            port:
              number: 80
