name: Deploy Prod
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Prod
        run: |
          aws eks update-kubeconfig --name ecom-prod
          helm upgrade --install ecom-ai devops/helm/ecommerce-ai -f devops/helm/ecommerce-ai/values-prod.yaml
